CREATE INDEX "branch_company_idx" ON "branch" USING btree ("companyId");--> statement-breakpoint
CREATE INDEX "company_balance_purchase_company_idx" ON "company_balance_purchase" USING btree ("companyId");--> statement-breakpoint
CREATE INDEX "driver_invite_company_idx" ON "driver_invite" USING btree ("companyId");--> statement-breakpoint
CREATE INDEX "driver_invite_driver_idx" ON "driver_invite" USING btree ("driverId");--> statement-breakpoint
CREATE INDEX "driver_company_idx" ON "drivers" USING btree ("companyId");--> statement-breakpoint
CREATE INDEX "driver_branch_idx" ON "drivers" USING btree ("branchId");--> statement-breakpoint
CREATE INDEX "driver_user_idx" ON "drivers" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "mission_company_idx" ON "missions" USING btree ("companyId");--> statement-breakpoint
CREATE INDEX "mission_date_idx" ON "missions" USING btree ("date");--> statement-breakpoint
CREATE INDEX "mission_status_idx" ON "missions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "mission_route_idx" ON "missions" USING btree ("routeId");--> statement-breakpoint
CREATE INDEX "mission_driver_idx" ON "missions" USING btree ("driverId");--> statement-breakpoint
CREATE INDEX "mission_vehicle_idx" ON "missions" USING btree ("vehicleId");--> statement-breakpoint
CREATE INDEX "mobile_user_driver_idx" ON "mobile_user" USING btree ("driverId");--> statement-breakpoint
CREATE INDEX "refresh_token_user_idx" ON "refresh_tokens" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "refresh_token_mobile_user_idx" ON "refresh_tokens" USING btree ("mobileUserId");--> statement-breakpoint
CREATE INDEX "role_company_idx" ON "role" USING btree ("companyId");--> statement-breakpoint
CREATE INDEX "route_company_idx" ON "routes" USING btree ("companyId");--> statement-breakpoint
CREATE INDEX "route_date_idx" ON "routes" USING btree ("date");--> statement-breakpoint
CREATE INDEX "route_status_idx" ON "routes" USING btree ("status");--> statement-breakpoint
CREATE INDEX "route_vehicle_idx" ON "routes" USING btree ("vehicleId");--> statement-breakpoint
CREATE INDEX "route_driver_idx" ON "routes" USING btree ("driverId");--> statement-breakpoint
CREATE INDEX "user_company_idx" ON "user" USING btree ("companyId");--> statement-breakpoint
CREATE INDEX "user_email_idx" ON "user" USING btree ("email");--> statement-breakpoint
CREATE INDEX "user_username_idx" ON "user" USING btree ("username");--> statement-breakpoint
CREATE INDEX "vda_company_idx" ON "vehicle_driver_assignments" USING btree ("companyId");--> statement-breakpoint
CREATE INDEX "vda_vehicle_idx" ON "vehicle_driver_assignments" USING btree ("vehicleId");--> statement-breakpoint
CREATE INDEX "vda_driver_idx" ON "vehicle_driver_assignments" USING btree ("driverId");--> statement-breakpoint
CREATE INDEX "vda_date_range_idx" ON "vehicle_driver_assignments" USING btree ("startDate","endDate");--> statement-breakpoint
CREATE INDEX "vehicle_company_idx" ON "vehicles" USING btree ("companyId");--> statement-breakpoint
CREATE INDEX "vehicle_branch_idx" ON "vehicles" USING btree ("branchId");--> statement-breakpoint
CREATE INDEX "vehicle_status_idx" ON "vehicles" USING btree ("status");